server:
  port: 8083

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: ancba-shrio-demo
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8088
        enabled: false

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
