server:
  port: 8186

spring:
  application:
    name: ancba-task-xxl
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8088
        enabled: false

  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8918

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

# xxl-job配置
xxl:
  job:
    admin:
      addresses: http://localhost:8380/xxl-job-admin
    executor:
      address:
      appname: ancba-task-xxl
      ip:
      port: 9876
      logpath: /logs/xxl-job/jobhandler
      logretentiondays: 15
    accessToken:
