server:
  port: 9999

spring:
  application:
    name: ancba-gateway
  cloud:
    nacos:
      # 注册中心
      discovery:
        server-addr: http://localhost:8918
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            # 不建议全部放开，建议使用nginx反向代理或者只开放前端域名
            # 允许携带认证信息
            # 允许跨域的源(网站域名/ip)，设置*为全部
            # 允许跨域请求里的head字段，设置*为全部
            # 允许跨域的method， 默认为GET和OPTIONS，设置*为全部
            # 跨域允许的有效期
            allow-credentials: true
            allowed-origins:
              - "http://localhost:5500"
              - "http://localhost:5501"
            allowed-headers: "*"
            allowed-methods:
              - OPTIONS
              - GET
              - POST
            max-age: 3600
      discovery:
        locator:
#          enabled: true
      routes:
        - id: blog-spring
          uri: lb://ancba-blog
          predicates:
            - Path=/ancba-blog/**
          filters:
            - StripPrefix=1
        - id: ancba-user
          uri: lb://ancba-user
          predicates:
            - Path=/ancba-user/**
          filters:
            - StripPrefix=1
