server:
  port: 8181

spring:
  application:
    name: ancba-authorizer-oauth2
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8088
        enabled: false
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8918

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS