server:
  port: 9092

spring:
  application:
    name: ancba-blog
  profiles:
    active: local
  boot:
    admin:
      client:
        url: http://localhost:8088

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS

logback:
  appName: blog-spring
  fileType: log
  logDir: logs