server:
  port: 8085

spring:
  application:
    name: ancba-user
  profiles:
    active: dev

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
