server:
  port: 8083

spring:
  application:
    name: ancba-user
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: http://localhost:8088
        enabled: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    health-check-url-path: /actuator/health
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
