# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
      

    # 登录到 阿里云镜像服务，使用 GitHub secrets 传入账号密码，密码被加密存储在 GitHub 服务器
    - name: Login to Aliyun
      uses: docker/login-action@v1
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_USER_NAME }}
        password: ${{ secrets.ALIYUN_PASSWORD }}

    - name: Push Docker Image
      run: |
        echo '=====开始上传镜像====='
        
        echo '=====开始上传ancba-admin====='
        docker push registry.cn-hangzhou.aliyuncs.com/ancba/ancba-admin:0.0.1-SNAPSHOT

        echo '=====开始上传ancba-authorizer-oauth2====='
        docker push registry.cn-hangzhou.aliyuncs.com/ancba/ancba-authorizer-oauth2:0.0.1-SNAPSHOT

        echo '=====开始上传ancba-blog====='
        docker push registry.cn-hangzhou.aliyuncs.com/ancba/ancba-blog:0.0.1-SNAPSHOT

        echo '=====开始上传ancba-gateway====='
        docker push registry.cn-hangzhou.aliyuncs.com/ancba/ancba-gateway:0.0.1-SNAPSHOT

        echo '=====开始上传ancba-shrio-demo====='
        docker push registry.cn-hangzhou.aliyuncs.com/ancba/ancba-shrio-demo:0.0.1-SNAPSHOT

        echo '=====开始上传ancba-task-xxl====='
        docker push registry.cn-hangzhou.aliyuncs.com/ancba/ancba-task-xxl:0.0.1-SNAPSHOT

        echo '=====开始上传ancba-user====='
        docker push registry.cn-hangzhou.aliyuncs.com/ancba/ancba-user:0.0.1-SNAPSHOT


        echo '=====镜像上传结束====='
